### ISSUE TITLE
No "TAB" character

### ISSUE THREAD

**Issue by Flappo420** [digabi/rich-text-editor#132]
I am using the digabi editor for school and I want to use the TAB charcter like there is in for example MS Word and other text editors.

**Comment by rossi-fi** [comment]
This is an issue with browsers; they use the tab key to jump to the next input. Please read through the [answers here](https://superuser.com/questions/67934/typing-the-tab-character-in-browser-text-boxes) for various OS and browser combinations. I tried CTRL+Option+Tab on MacOS and it seems to work.

**Comment by Flappo420** [comment]
JS script to check if you're in the text editor and replace the TAB input to change fields with either a system like MS Word with specific stops or "ALT+09". Or is the TAB to change fields a neccessary feature?

**Comment by shnigi** [comment]
> JS script to check if you're in the text editor and replace the TAB input to change fields with either a system like MS Word with specific stops or "ALT+09". Or is the TAB to change fields a neccessary feature?

I Believe tab element change is for web usability and is a feature that blind people might use for navigating around site. It is the default and expected behavior for web browser. It should not be changed to work like MS Word.

**Comment by Flappo420** [comment]
Okay!
