### ISSUE TITLE
Pasting formulas to direct example not working

### ISSUE THREAD

**Issue by shnigi** [digabi/rich-text-editor#156]
Copying a formula from https://cheat.abitti.fi/ and then pasting it to the demo https://math-demo.abitti.fi/ works as expected but pasting to the rich-text-editor direct example doesn't work. I experienced this same issue on my app. Any hints what could be wrong? http://digabi.github.io/rich-text-editor/ The formula just flashes quickly and disappears. No latex image.

**Comment by eeroan** [comment]
It's not supported, since the direct example uses serversideless implementation hack for rendering the formula.

**Comment by shnigi** [comment]
It doesn't work in localhost either. Could you provide more information how it works on the current demo version? I need to implement this feature.
