### ISSUE TITLE
Pasting formulas not working

### ISSUE THREAD

**Issue by shnigi** [digabi/rich-text-editor#165]
When you clone this repository and try to copy paste math from https://cheat.abitti.fi/ it doesn't work as in the https://math-demo.abitti.fi/ I would need more information how the serverside rendering should be implemented in order to get it working like in the official versions. Ticket is related to my earlier ticket: https://github.com/digabi/rich-text-editor/issues/156 Could you provide more information how to get the copy paste working on localhost?

**Comment by eeroan** [comment]
The problem is that the base url of the svg should match the with the base url of the editor.

If you replace `math-demo.abitti.fi` with `localhost:5000` here https://github.com/digabi/koe-ohje/blob/aa7d6584d62dd7710d2438f46ba42a0474bb9045/webpack.config.js#L47 and then run `yarn build:internet; yarn start`
you should be able to copy from http://localhost:8080 and paste to http://localhost:5000/test/tests.html.

**Comment by shnigi** [comment]
I managed to copy paste to MathQuill box but not in the 1 and 2 elements where the Abitti editori is implemented. So basically does this mean that we are not able to copy math formulas from math-demo.abitti.fi and then paste them into our own Abitti editori which is running under another domain? So this is a cross origin issue actually?

**Comment by eeroan** [comment]
The idea is to copy directly to the answer-box without the need to open the formula editor because koe-ohje copies the img instead of the text. It's cross origin and/or sanitation issue, not sure.

**Comment by shnigi** [comment]
Yep that is exactly what we are trying to do, implement copy paste from  https://cheat.abitti.fi/  to our Abitti editor without the need to open the formula editor. If you look at the following GIF I am trying to copy paste a math formula to our Abitti editor. The latex syntax quickly flashes in the view but doesn't generate image. 
![latexabitticopypaste](https://user-images.githubusercontent.com/4188125/103638460-9e34b180-4f55-11eb-8cb8-f951f20681b5.gif)

Then if you look at the network request tab the request is just fine and I can see the SVG image generated in the response.
![Selection_009](https://user-images.githubusercontent.com/4188125/103638691-ea7ff180-4f55-11eb-9c32-d95dd1a035a5.png)

For some reason the received image doesn't show up in the editor and I am trying to figure out if there is anything we can do about it.

**Comment by kunring** [comment]
Check issue #418 for a workaround
