### ISSUE TITLE
Unwelcome automatic changing of LaTeX code

### ISSUE THREAD

**Issue by ollpu** [digabi/rich-text-editor#25]
When writing custom LaTeX in the editor, some of it is not supported by MathQuill (the wysiwyg-editor), but is supported by the final renderer. This is fine, and I can use all the functionality. However, when reopening the equation for editing, all raw LaTeX is reinterpreted and a lot of code that isn't supported by MathQuill changes.

## Example
I write some LaTeX that isn't quite supported by MathQuill:
![Step 1](https://user-images.githubusercontent.com/7241014/36835158-f8f990c4-1d3d-11e8-95b3-80533ed2a2ab.png)

Exit the editor and it displays fine:
![Step 2](https://user-images.githubusercontent.com/7241014/36835300-6ed70f74-1d3e-11e8-8fd9-7618ffaf3784.png)

But, when reopening the editor, the code has changed:
![Step 3](https://user-images.githubusercontent.com/7241014/36835360-9b7ccce4-1d3e-11e8-965d-2f032df94728.png)

And finally, closing the editor again, the final render has changed.
![Step 4](https://user-images.githubusercontent.com/7241014/36835390-c13c42de-1d3e-11e8-8c09-bff373e8dbb8.png)

The same kind of behaviour can be observed with many other features as well, such as symbol names changing to their aliases (not a deal-breaker necessarily), or writing  "minimum" and not wanting it to be changed to "\min imum".

**Comment by eeroan** [comment]
Fixed by v3.5.0

**Comment by ollpu** [comment]
The issue, such as in the given examples, seems to persist in the latest version. Out of curiosity, is there a reason to not disable the reinterpretation?
