### ISSUE TITLE
Mhchem not rendering in preview but works otherwise

### ISSUE THREAD

**Issue by juusolain** [digabi/rich-text-editor#260]
When using mhchem with \ce, the result does not render on the preview view. Like here:
![image](https://user-images.githubusercontent.com/12936560/114833543-605aeb00-9dd8-11eb-881d-a86c1e9b976f.png)
But it does render after closing the field:
![image](https://user-images.githubusercontent.com/12936560/114833588-6e107080-9dd8-11eb-8131-b0008f2be0b1.png)

Also, \ce should probably have a shortcut in the top bar if this issue is fixed.

**Comment by eeroan** [comment]
This is a bug in mathquill library
