### ISSUE TITLE
Rich text editor example font is different to Math demo

### ISSUE THREAD

**Issue by shnigi** [digabi/rich-text-editor#300]
Create for example this latex code: 

`ax^2+bx+c=0 `

in rich text editor demo http://digabi.github.io/rich-text-editor/
Then create the same latex code in Math demo: https://math-demo.abitti.fi/ 

The SVG font is slightly different. What is causing this and what is the math-demo configuration for fonts?

**Comment by kinnala** [comment]
Seems that http://digabi.github.io/rich-text-editor/ is specifying `font: 'STIX-Web'`. I tried removing that in my simple offline version of rich-text-editor (https://github.com/kinnala/vihko) and seem to get a font which is similar to https://math-demo.abitti.fi/:

Without `font: 'STIX-Web'`:
![Kuvakaappaus - 2022-01-13 09-37-47](https://user-images.githubusercontent.com/973268/149286299-266849d0-f126-4d2b-8bc1-4c38938d4ff4.png)

With `font: 'STIX-Web'`:
![Kuvakaappaus - 2022-01-13 09-37-47](https://user-images.githubusercontent.com/973268/149286351-c014611a-8095-4c6c-919c-40b3f1a0c87b.png)
