### ISSUE TITLE
Static version

### ISSUE THREAD

**Issue by piehei** [digabi/rich-text-editor#33]
Hi

I'm exploring whether it would be feasible to use the Abitti editor in an e-learning system. We already have exercises where students type into a textarea element but that's rather horrible. The easiest way to utilize the editor would be to compile the whole thing into a static site without the Node server. This would, of course, drop out the upload functionality, but whatever.

From my five-minute testing it seems that once you fire up the editor, the only realtime connections are required for the math.svg in order to render something nice on the screen.

**Question**: when this architecture was chosen, was it investigated whether this whole thing https://github.com/digabi/rich-text-editor/blob/master/server/mathSvg.js could be done *on the client* without any additional HTTP requests? It should be a matter of finding Latex SVG libraries or something like that, the SVG construction is a trivial thing in itself.

If the SVG rendering could be done in the client AND if I'm not missing something critical, I think it would not be too big a hurdle to build a static version which one could use by just including necessary CSS, JS, and font files and putting some `<div id="editor-here">` in their own templates.

Please note I really haven't dug deep here. Just some ideas, I could be missing a lot.

Thanks a lot!

**Comment by mplattu** [comment]
Please let me know whether you find [this demo](http://digabi.github.io/rich-text-editor/) helpful.

**Comment by mplattu** [comment]
Since it looks for me like there is nothing we should/can do on our side I'll close this. Please re-open if necessary.

**Comment by piehei** [comment]
Thanks!
