### ISSUE TITLE
Problems with powers inside LaTeX editor

### ISSUE THREAD

**Issue by Uumas** [digabi/rich-text-editor#35]
Here are a few examples of the issues which I've found with rendering powers written incorrectly in LaTeX

![image](https://user-images.githubusercontent.com/10895201/50047937-87019d80-00c8-11e9-8546-e8a9417d7d19.png)

It seems to me like it's trying to automatically fix the syntax, but that only happens when re-entering the editor instead of right away when exiting which causes the rendering to change. This shouldn't cause any huge problems, but it could cause some small annoyances.

**Comment by eeroan** [comment]
Closing, unless someone is willing to make a pull request.
