### ISSUE TITLE
Issue with \deg(ree)

### ISSUE THREAD

**Issue by Apeli** [digabi/rich-text-editor#363]
When typing \deg to the LaTex-field in the editor, the preview shows the degree symbol (°) correctly. But after you unfocus the LaTex field, it turns into plain text "deg". After activating the editor again, the LaTex is now \degree, the preview is again correct, but after unfocusing it the symbol/formula fails.

There is a shortcut button in the toolbar, but some students prefer typing it in LaTex.

**Comment by Finnduino** [comment]
Any update on this bug? I've been patiently waiting for a fix for years at this point, as I find this as one of the biggest annoyances when having to do anything with degrees.

**Comment by eeroan** [comment]
This is fixed so that it remains unicode character, since mathjax is unable to render \deg or \degree
