### ISSUE TITLE
Extending formula doesn't render correctly 

### ISSUE THREAD

**Issue by shnigi** [digabi/rich-text-editor#379]
Extending formula renders wrong. 

Latex: `^{X\text{)}}\frac{X}{X}`

![Matikkaeditori - Google Chrome_042](https://user-images.githubusercontent.com/4188125/136948056-eb620b30-0415-488b-b20b-4241d019d5af.png)

As you can see the x) renders almost in the middle of the formula. Should be on top like where it is when typing the code.

**Comment by kinnala** [comment]
I suggest this is fixed by using `\strut^{x\text{)}}\frac{a}{b}`. Here is a comparison:
![Kuvakaappaus - 2022-01-13 09-47-23](https://user-images.githubusercontent.com/973268/149287562-3546ff0d-03a8-4f13-b61d-57501cf26b6c.png)
