### ISSUE TITLE
Toolbar blocks the editor

### ISSUE THREAD

**Issue by kunring** [digabi/rich-text-editor#419]
The toolbar can block the editor field if the editor field is positioned near the top of the page and the viewport width is scaled down. Examples captured on https://math-demo.abitti.fi/ with the header and instruction text removed.

![image](https://user-images.githubusercontent.com/25564242/145727587-0affa5a9-1664-4b8f-8a38-d270db80f7e3.png)
![image](https://user-images.githubusercontent.com/25564242/145727604-d8b6ddca-56c2-4cc6-a806-81df0d2b509d.png)
![image](https://user-images.githubusercontent.com/25564242/145727620-06b355a9-d282-4025-b723-0ec3a47bc6d3.png)
![image](https://user-images.githubusercontent.com/25564242/145727664-5af96c76-5060-424a-910e-eba3f85e3a5f.png)

**Comment by eeroan** [comment]
Known issue, but not a problem in matriculation examination.
