### ISSUE TITLE
Inconsistent behaviour with placement of new formulas

### ISSUE THREAD

**Issue by kunring** [digabi/rich-text-editor#420]
### New formula with enter
Starting a formula (and writing any content) and ending it with enter should place the formula (where it would be placed with any formula exit method) and start a new formula, which if finished, will be positioned after the previous formula and 1 newline.

This behaviour gets inconsistent in the following situation:
Place a newline (and keep your caret at the start of the new line)
Write a formula (with content)
End this formula with enter

The inconsistent behaviour is that this will start the new formula after 2 newlines instead of 1.
![Peek 2021-12-12 22-38](https://user-images.githubusercontent.com/25564242/145728771-8c29aee9-7d81-4519-970d-348115c8865b.gif)
Keys pressed here: enter, ctrl+e, a, enter, b, esc

The new formula should be placed after 1 newline.

**Comment by eeroan** [comment]
minor issue
