### ISSUE TITLE
Stepping inside \mathbb breaks things

### ISSUE THREAD

**Issue by kunring** [digabi/rich-text-editor#439]
Within formulas \mathbb{} is used to display the characters ℤℝℕℚ 

The problem is this can be accidentally stepped into:
![Peek 2022-01-21 20-45](https://user-images.githubusercontent.com/25564242/150583046-c5e21ca5-6e0c-40d2-b1a7-d9b702fde647.gif)

Writing inside mathbb doesn't seem to be intended - or at least wasn't tested properly.
Stepping inside it should probably just be disabled entirely.

### Here are some of the issues I quickly found

![Peek 2022-01-21 20-50](https://user-images.githubusercontent.com/25564242/150583613-adcc79d1-87f2-456d-a876-09e70b290197.gif)
The behavior above happens with (), [], {}, | |, 

It erases latex brackets, which breaks half of the formulas
![Peek 2022-01-21 20-56](https://user-images.githubusercontent.com/25564242/150584327-73e6dda0-12a1-4dbc-8ff6-75e2abc3fbfb.gif)

\lim, upper index and lower index multiply on interaction:
![Peek 2022-01-21 21-01](https://user-images.githubusercontent.com/25564242/150584982-0e75a4c0-fada-4f0e-9771-6fac3a11e60f.gif)

**Comment by eeroan** [comment]
I'm afraid there's no way to prevent this
