### ISSUE TITLE
Adding line breaks breaks preview

### ISSUE THREAD

**Issue by Uumas** [digabi/rich-text-editor#44]
Adding a line break `\\` in LaTeX makes the preview disappear completely. This is extremely inconvenient. Also typing something to the preview in that state will make you lose everything. Here's a screenshot:
![image](https://user-images.githubusercontent.com/10895201/57088740-985fe500-6d0b-11e9-896b-b8953e1085cb.png)

**Comment by ruumis** [comment]
MathQuill, the component that renders the LaTeX code doesn't allow multiple lines. The easy workaround is to create multiple formulas on different rows. Also, if you know LaTeX, the output of your code will show in the answer, even if it not shown in the preview.
