### ISSUE TITLE
Text caret positions weirdly with Firefox

### ISSUE THREAD

**Issue by kunring** [digabi/rich-text-editor#441]
### Chromium
![image](https://user-images.githubusercontent.com/25564242/150635697-64d82563-d029-4ffa-b53e-d9290a677f88.png) ![image](https://user-images.githubusercontent.com/25564242/150635690-4bf785a3-d55b-401d-bfaa-0361e7ed971c.png)

### Firefox
![image](https://user-images.githubusercontent.com/25564242/150635663-36fc7b77-5a69-4ef7-8146-0ccb1bb1c540.png) ![image](https://user-images.githubusercontent.com/25564242/150635659-36b9ec98-68c1-4559-bec3-7431fc0ce98d.png)

**Comment by eeroan** [comment]
This is a firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=904846
