### ISSUE TITLE
Implement undo & redo features for the math editor

### ISSUE THREAD

**Issue by m1ksu** [digabi/rich-text-editor#454]
(Near) duplicate of https://github.com/digabi/mathquill/issues/10

The lack of an undo function is an obvious flaw in Mathquill (the component used for writing the LaTeX code) and by extension the rich text editor as a whole, as every wrong or accidental keypress risks the user losing whatever they have been typing into the equation field. To save on the frustration such a thing causes, the addition of an undo and redo feature would be highly appreciated.

This has been on open issue on the main Mathquill repository for almost 11 years now. A few people have voiced their frustrations and shared their own implementations for the feature on it: https://github.com/mathquill/mathquill/issues/5.

Perhaps one of these (or an original implementation) could be implemented into the Digabi project's fork of Mathquill at https://github.com/digabi/mathquill?

**Comment by eeroan** [comment]
Undo (version history) is already implemented in the examination system.
