### ISSUE TITLE
Add support for \xrightarrow

### ISSUE THREAD

**Issue by Uumas** [digabi/rich-text-editor#52]
\xrightleftharpoons already works (but \rightleftharpoons doesn't in preview), so could you add support for \xrightarrow (and \xleftarrow) also. This would help in writing some chemical reactions.

**Comment by eeroan** [comment]
Why `\rightleftharpoons` is needed and `\xrightleftharpoons` is not sufficient?

`\xrightarrow` is not supported by MathJax, so there is no mouch we can do.

**Comment by Uumas** [comment]
`\rightleftharpoons` is more of a style question. Not having empty boxes around the harpoons feels cleaner.
About MathJax not supporting `\xrightarrow` (or some other things) you can do everything about it. It's an open source project so you can fork it and even commit back to upstream to help others who'd have use for the functionality.

**Comment by eeroan** [comment]
This is not a priority for us. And the button bar is also pretty full

**Comment by Uumas** [comment]
That's quite stupid reasoning. You already have many commands which work, but are not available in the bar and many commands which don't really need to be in the bar. It also should be a priority, because I've talked to a few students who have taken the chemistry matriculation exam and would have needed that.
