### ISSUE TITLE
Bug: Automatic replacement of < and > to \lt and \gt breaks mhchem's \ce commands.

### ISSUE THREAD

**Issue by m1ksu** [digabi/rich-text-editor#533]
Behaviour introduced in #436 conflicts with [mchem's `\ce` command](https://docs.moodle.org/400/en/Chemistry_notation_using_mhchem) by replacing reaction arrows, which use < and >, with \lt and \gt, which do not render correctly within chemical reactions. The problem can be mitigated by manually replacing \lt and \gt every time a formula containing \ce is opened. 

Example of before and after opening a formula containing a reaction written using `\ce`:
![image](https://user-images.githubusercontent.com/22960424/185897119-22f55f72-2adc-4fe2-b9e6-431f3911ca31.png)

To reproduce the issue:

1. Create a formula with the following LaTeX code: `\ce{2H2 + O2 -> 2H2O}`.
2. Unfocus the LaTeX editor by clicking outside of the formula.
3. Refocus the formula. The LaTeX code now reads `\ce{2H2 + O2 -\gt  2H2O}`, which is not desired behaviour.
4. Unfocus the LaTeX editor. The chemical reaction now shows a broken reaction arrow.

**Comment by eeroan** [comment]
Sorry to hear, but we only focus on features possible to produce using the UI and not breaking the wysiwyg.
