### ISSUE TITLE
Problems with rendering \square

### ISSUE THREAD

**Issue by Apeli** [digabi/rich-text-editor#74]
Hi folks,

we had issues in rendering \square -symbols with the math editor. On https://math-demo.abitti.fi/ it works, but the other demo (http://digabi.github.io/rich-text-editor/) has the same problem. What is the difference between those two?

**Comment by sluukkonen** [comment]
It seems to cause an error on the latter site. Not sure what the issue is yet.

![image](https://user-images.githubusercontent.com/39655/91979460-7d054f80-ed2e-11ea-9241-066ddf7c8ac7.png)

**Comment by Apeli** [comment]
Apparently the problematic one is the "standalone" version, the former version with server-side rendered svg works.

**Comment by sluukkonen** [comment]
MathJax seems to render a Unicode [white medium square](https://www.fileformat.info/info/unicode/char/25fb/index.htm) character, which can't be converted to base64 with `btoa`.

Exceprt from the generated SVG:

```svg
<text font-family="STIXGeneral,'Arial Unicode MS',serif" font-style="italic" stroke="none" transform="scale(51.461) matrix(1 0 0 -1 0 0)">◻</text>
```

**Comment by Apeli** [comment]
Is the server-side rendered svg -version available somewhere? Removing MathJax from the equation would be nice.
